### ISSUE TITLE
nice

### ISSUE THREAD

**Issue by fanxiaofan577** [gzyunke/test-k8s#2]
就喜欢这种干脆利落的讲，其他的废话连篇麻烦的很

**Comment by hus-qin** [comment]
[root@VM-0-17-centos service]# kubectl logs --namespace=kube-system -l k8s-app=kube-dns
[ERROR] plugin/errors: 2 6358316714611568719.5289462307456028856. HINFO: read udp 10.244.0.3:57781->183.60.83.19:53: i/o timeout

这是dns出现了什么问题吗？我没办法在两个pod之间进行通讯

**Comment by gzyunke** [comment]
你这个大概率是网络插件没安装好，你看下最新的文档，有补充可以安装其他网络插件，试下吧

**Comment by bllon** [comment]
Error from server (BadRequest): error when creating "mogo-storage.yaml": StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal object into Go struct field PodSpec.spec.template.spec.containers of type []v1.Container

持久化本地挂载磁盘报这个错，是文档中给yaml文件内容有问题吗

**Comment by gzyunke** [comment]
> 

你是不是改了这个配置，或者你的安装的k8s版本跟我的不一样，导致识别格式不对了，这个文件是没问题的

**Comment by bllon** [comment]
> > 
> 
> 你是不是改了这个配置，或者你的安装的k8s版本跟我的不一样，导致识别格式不对了，这个文件是没问题的



> > 
> 
> 你是不是改了这个配置，或者你的安装的k8s版本跟我的不一样，导致识别格式不对了，这个文件是没问题的

我用的是minikube，版本1.30.1，文件内容是直接复制的
kubectl版本:
Client Version: v1.25.9
Kustomize Version: v4.5.7
Server Version: v1.26.3
